**Array**

In [18]:
import numpy as np
zero=np.zeros((4,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Random Function**

In [20]:
#rand() function #np.random.rand(n)-->1D array ,np.random.rand(m,n)-->2D array
Random=np.random.rand(2,3)
print(Random)
#randn() function #close to zero ,include positive and Negative
Random_1=np.random.randn(4)
print(Random_1)
#ranf() function #Random floats in [0, 1)
Random_2=np.random.ranf(5) #1D array
Random_3=np.random.ranf((3,3)) #2D array
print(Random_2,Random_3)
#Randint(low, high=None, size=None)
Random_4=np.random.randint(3,10,(4,4))
#Random_4=np.random.randint(3,10,5) #[8 4 9 5 3]
print(Random_4)

[[0.47255287 0.44644147 0.94809248]
 [0.00472023 0.27500493 0.48667612]]
[-0.24043507 -0.6592043   0.49231002 -0.52456663]
[0.69764824 0.03454804 0.81822118 0.77579864 0.06406288] [[0.36584719 0.8192795  0.56978252]
 [0.64959289 0.33892737 0.11767941]
 [0.6578185  0.62072193 0.99473436]]
[[3 4 7 9]
 [8 5 5 9]
 [5 5 5 8]
 [6 6 7 7]]


**Data Type**

In [62]:
Array_1=np.array(["A",45,"Foysal"])
Array_1.dtype #U11 is the subset of string
Array_2=np.array([1,3,4,5,6,7,True])

**Arithmetic Operation**

In [210]:
A=np.array([1,3,4,5,7])
B=np.array([4,5,6,3,5])
C=A+5 #add valuefg
C_1=np.add(5,A)
D=A+B #add two array
D_1=np.add(A,B)
E=B*5 #multiplication
E_1=np.multiply(B,5)
F=A/2 #Division
F_1=np.divide(A,2)
G=C-A #Substaction
G_1=np.subtract(C,A)
H=A%B #Mod
H_1=np.mod(A,B)
I=B**2 #Power
I_1=np.power(B,2)
J=1/A #reciprocal
J_1=np.reciprocal(1/A)
print(C,C_1,D,D_1,E,E_1,F,F_1,G,G_1,H,H_1,I,I_1,J,J_1)

[ 6  8  9 10 12] [ 6  8  9 10 12] [ 5  8 10  8 12] [ 5  8 10  8 12] [20 25 30 15 25] [20 25 30 15 25] [0.5 1.5 2.  2.5 3.5] [0.5 1.5 2.  2.5 3.5] [5 5 5 5 5] [5 5 5 5 5] [1 3 4 2 2] [1 3 4 2 2] [16 25 36  9 25] [16 25 36  9 25] [1.         0.33333333 0.25       0.2        0.14285714] [1. 3. 4. 5. 7.]


**Arithmetic Function**

In [275]:
Array_2=np.array([31,23,14,35,67,15,43,5,5,16,7,53,32,22])
np.min(Array_2) #find the min number
np.max(Array_2) #find the max number
np.argmin(Array_2) #Position of index

print(np.min(Array_2),np.max(Array_2),np.argmin(Array_2),np.argmax(Array_2))
#sqrt
print(np.sqrt(Array_2))
#sin(x) and cos(x)
Array_3=np.array([1,3,4,5,6])
print(np.sin(Array_3),np.cos(Array_3))
#Cumsum #Arc Adition
print(np.cumsum(Array_3))

5 67 7 4
[5.56776436 4.79583152 3.74165739 5.91607978 8.18535277 3.87298335
 6.55743852 2.23606798 2.23606798 4.         2.64575131 7.28010989
 5.65685425 4.69041576]
[ 0.84147098  0.14112001 -0.7568025  -0.95892427 -0.2794155 ] [ 0.54030231 -0.9899925  -0.65364362  0.28366219  0.96017029]
[ 1  4  8 13 19]


***Shape***

In [328]:
#Reshape Changes the shape without modifying 
var=np.array([1,4,7,2,9,8,9,7])
Reshape=np.reshape(var,(4,2))
#Resize Changes the shape and can modify
var_1=np.array([1,4,3,10,5,5,3,4,3,2,3,5])
Resize=np.resize(var,(3,4))
Resize_1=np.resize(var_1,(4,5))

print(Reshape,Resize,Resize_1)

[[1 4]
 [7 2]
 [9 8]
 [9 7]] [[1 4 7 2]
 [9 8 9 7]
 [1 4 7 2]] [[ 1  4  3 10  5]
 [ 5  3  4  3  2]
 [ 3  5  1  4  3]
 [10  5  5  3  4]]


**Broadcasting**

In [359]:
Array_4=np.random.randint(3,10,(3,1))
Array_5=np.random.randint(1,7,(1,4))
print(Array_4+Array_5) #A is broadcast across columns, B across rows
Array_6=np.random.randint(3,10,(4,1))
Array_7=np.random.randint(3,10,(3,)) #becomes (1, 3)
print(Array_6+Array_7) #Error->not equal and not 1


[[ 7  9 12 12]
 [ 7  9 12 12]
 [ 6  8 11 11]]
[[13 13  8]
 [12 12  7]
 [17 17 12]
 [13 13  8]]


**Array Indexing and Slicing**

In [50]:
#Indexing
Array_8=np.array([12,3,4,5,56,6,7,8,98,64,3,2,353,3,53])
Array_9=np.random.randint(2,4,(3,3))
Array_10=np.array([[[2, 3 ,2],[2, 3 ,10]],[[2, 3 ,3],[2, 3 ,2]]])
print(Array_8[5],Array_9,Array_10.ndim,Array_10[0,1,2])
#Slicing [4:13:2]=[start:end:step]
print(Array_8[4:13:2],Array_8[-11:-2:2],Array_10[0:1],Array_10[1,0,1:3])

6 [[3 3 3]
 [2 3 3]
 [2 3 2]] 3 10
[ 56   7  98   3 353] [ 56   7  98   3 353] [[[ 2  3  2]
  [ 2  3 10]]] [3 3]


**<span style="background-color:yellow">Iterating Numpy Array<span>**

In [80]:
var_2=np.array([1,3,4,3,7,8])
for i in var_2:
    print(i)
var_3=np.array([[1,3,4,5],[5,3,3,6]])
for j in range(var_3.shape[0]):#rows
    for k in range(var_3.shape[1]):#Columns
     print(f"var_3[{j}][{k}] = {var_3[j][k]}")

for l in np.nditer(var_3):
    print(l)
for i, d in np.ndenumerate(var_3):
    print(i, d)

1
3
4
3
7
8
var_3[0][0] = 1
var_3[0][1] = 3
var_3[0][2] = 4
var_3[0][3] = 5
var_3[1][0] = 5
var_3[1][1] = 3
var_3[1][2] = 3
var_3[1][3] = 6
1
3
4
5
5
3
3
6
(0, 0) 1
(0, 1) 3
(0, 2) 4
(0, 3) 5
(1, 0) 5
(1, 1) 3
(1, 2) 3
(1, 3) 6


***Copy Vs View***

In [39]:
import numpy as np
Value=np.array([1,3,7,6,7,7])
copy=Value.copy() #Create new data,doesnot affect origin data,Independent
View=Value.view() #shares data,Affects origin data,Dependent
copy[2]=4
View[2]=0

print(copy,Value,View)


[1 3 4 6 7 7] [1 3 0 6 7 7] [1 3 0 6 7 7]


*Join Array and Split Function*

In [117]:
Array_1=np.array([1,2,3,4,5,6])
Array_2=np.array([7,8,9,1,4,0])
Result_1=np.concatenate((Array_1,Array_2),axis=0)
Array_3=np.array([[1,3],[3,5]])
Array_4=np.array([[2,7],[5,7]])
Result_2=np.concatenate((Array_3,Array_4),axis=1)
print(Array_1,Array_2,Array_3,Array_4,Result_1,Result_2)
Result_3=np.stack((Array_1,Array_2),axis=0)#axis=0 Means row ,axis=1 means Column
print(Result_3)
Result_4=np.stack((Array_3,Array_4),axis=0)#Stack increase +1 dimension
Result_5=np.stack((Array_3,Array_4),axis=1)
print(Result_4,Result_5)
#HStack And VStack for 1D array
Result_6=np.hstack((Array_1,Array_2)) # horizontal stack(column-wise)
print(Result_6) #[1 2 3 4 5 6 7 8 9 1 4 0] combine and convert into a 1D Array
Result_7=np.vstack((Array_1,Array_2)) #vertical stack(row-wise)
print(Result_7) #[[1 2 3 4 5 6][7 8 9 1 4 0]] convert into a 2D Array
#HStack And VStack for 2D array
Result_8=np.hstack((Array_3,Array_4)) # horizontal stack(column-wise)
print(Result_8) #[[1 3 2 7][3 5 5 7]] combine and convert into a 2D Array
Result_9=np.vstack((Array_3,Array_4)) #vertical stack(row-wise)
print(Result_9,Result_9.ndim) #[[1 3][3 5][2 7][5 7]] All arange row by row.
#Split
Split_1=np.split(Array_1,3)
Split_2=np.split(Array_2,2)
print(Split_1,Split_2)


[1 2 3 4 5 6] [7 8 9 1 4 0] [[1 3]
 [3 5]] [[2 7]
 [5 7]] [1 2 3 4 5 6 7 8 9 1 4 0] [[1 3 2 7]
 [3 5 5 7]]
[[1 2 3 4 5 6]
 [7 8 9 1 4 0]]
[[[1 3]
  [3 5]]

 [[2 7]
  [5 7]]] [[[1 3]
  [2 7]]

 [[3 5]
  [5 7]]]
[1 2 3 4 5 6 7 8 9 1 4 0]
[[1 2 3 4 5 6]
 [7 8 9 1 4 0]]
[[1 3 2 7]
 [3 5 5 7]]
[[1 3]
 [3 5]
 [2 7]
 [5 7]] 2
[array([1, 2]), array([3, 4]), array([5, 6])] [array([7, 8, 9]), array([1, 4, 0])]


**Search/Find Index**

In [154]:
Array=np.array([1,2,4,5,6,7])#index find
x=np.where((Array%2!=0))
print(x)
val=3
y=np.searchsorted(Array,val)#find that where is the position of 3
print(y)
val_1=[4,0,15,4,13]
z=np.searchsorted(Array,val_1)
print(z)

(array([0, 3, 5], dtype=int64),)
2
[2 0 6 2 6]


<span style="color:red">Sort Array</span>

In [162]:
Array=np.array([7,3,8,19,12,4,10])
print(np.sort(Array))
Array_1=np.array(['a','N','f','t','B'])
print(np.sort(Array_1))

[ 3  4  7  8 10 12 19]
['B' 'N' 'a' 'f' 't']


`Filter Array`

In [184]:
arr = np.array([10, 25, 30, 15, 50])
result = arr[(arr >= 10) & (arr <= 20)]
print(result)  

[10 15]


`Arithmetic Functions`

In [237]:
#Suffles
array=np.array([2,3,7,2,3,3,8,9,4,3])
array_1=np.array([[[1,3],[4,7]],[[3,6],[1,3]]])
np.random.shuffle(array)#Order is randomly changed
np.random.shuffle(array_1)
print(array)
print(array_1)
#Unique
x=np.unique(array)
x_1=np.unique(array_1)
print(x)
print(x_1) #sorted list without duplicate from 2/3D array


[4 2 3 8 9 3 7 3 3 2]
[[[1 3]
  [4 7]]

 [[3 6]
  [1 3]]]
[2 3 4 7 8 9]
[1 3 4 6 7]


In [247]:
#Resize 
array=np.array([2,3,7,2,3,3,8,9,4,3])
array_1=np.array([[[1,3],[4,7]],[[3,6],[1,3]]])
y=np.resize(array,(2,3))
y_1=np.resize(array_1,(2,2))
y_2=np.resize(array_1,(4,4))
y_3=np.resize(array_1,(3,4))
print(y)#Repeats/Randomly Select data if the new shape is larger/small
print(y_1,y_2,y_3)

[[2 3 7]
 [2 3 3]]
[[1 3]
 [4 7]] [[1 3 4 7]
 [3 6 1 3]
 [1 3 4 7]
 [3 6 1 3]] [[1 3 4 7]
 [3 6 1 3]
 [1 3 4 7]]


In [259]:
#Flatten function
#converting a multi-dimensional array into a 1D array.Returns Copy
array_1=np.array([[[1,3],[4,7]],[[3,6],[1,3]]])
flat=array_1.flatten()
print(flat)
#Reval
#Returns a view if possible, or a copy otherwise.
flat_view = array_1.ravel()
print(flat_view) 
#Reshape
#Returns view
flat_reshape = array_1.reshape(-1)
print(flat_reshape)  

[1 3 4 7 3 6 1 3]
[1 3 4 7 3 6 1 3]
[1 3 4 7 3 6 1 3]


In [285]:
#Insert Function for 1D array
variable=np.array([1,4,5,6,7,8,9])
v=np.insert(variable,1,3) #(array,index,value)
#v=np.insert(variable,(3,4),10) #(array,index,value)
v=np.insert(variable,7,(3,4)) #(array,index,value)
#Extra Practics
x=np.concatenate((variable,v))
y=np.sort(x)
z=np.unique(y)#Unique returns sort+unique list
z_1=np.unique(x)
print(v,x,y,z,z_1)

[1 4 5 6 7 8 9 3 4] [1 4 5 6 7 8 9 1 4 5 6 7 8 9 3 4] [1 1 3 4 4 4 5 5 6 6 7 7 8 8 9 9] [1 3 4 5 6 7 8 9] [1 3 4 5 6 7 8 9]


In [299]:
#Insert Function for 2D array
variable=np.array([[1,3,5,2,5],[9,3,4,5,1],[1,6,4,19,0]])
var=np.insert(variable,2,(2,3,7),axis=1) #column
var_1=np.insert(variable,3,(9,0,2,5,7),axis=0) #rows
print(var)
print()
print(var_1)

[[ 1  3  2  5  2  5]
 [ 9  3  3  4  5  1]
 [ 1  6  7  4 19  0]]

[[ 1  3  5  2  5]
 [ 9  3  4  5  1]
 [ 1  6  4 19  0]
 [ 9  0  2  5  7]]


In [313]:
#Append function for 1D array
#np.append(array, values, axis=None)
array=np.array([1,2,3,4,5])
array_1=np.array([[2,5],[3,9],[8,4]])
arr=np.append(array,(6,7,8))
arr_2=np.append(array_1,[[2,5]],axis=0)
#arr_2=np.append(array_1,[[2,5]],axis=0)
print(arr,arr_1,arr_2)

[1 2 3 4 5 6 7 8] [[2 5]
 [3 9]
 [8 4]
 [2 5]] [[2 5]
 [3 9]
 [8 4]
 [2 5]]


**Matrix**

In [31]:
import numpy as np
var=np.matrix([[1,2,3],[4,5,7],[1,4,5]])
var_1=np.matrix([[2,9],[4,5],[2,6]])
var_2=np.matrix([[6,3],[8,5],[8,4]])

print(type(var))
#Addition,Cross Product,Substruction,dot Product
print(var*var_1) #3*3 and 3*2 = 3*2
print()
print(var.dot(var_2)) #3*3 and 3*2 = 3*2
print(var_1+var_2)
print(var_1-var_2)

<class 'numpy.matrix'>
[[ 16  37]
 [ 42 103]
 [ 28  59]]

[[ 46  25]
 [120  65]
 [ 78  43]]
[[ 8 12]
 [12 10]
 [10 10]]
[[-4  6]
 [-4  0]
 [-6  2]]


***Matrix Feature***

In [70]:
#Transpose #transpose(a, axes=None)
print(var)
print(np.transpose(var))
#Swapaxes #swapaxes(a, axis1, axis2)
print(np.swapaxes(var,0,1))
#Inverse #np.linalg.inv() 
#linalg is short for Linear Algebra.
print(np.linalg.inv(var))
#Moore-Penrose Pseudo-Inverse
#If the matrix is not square or not invertible
print(np.linalg.pinv(var_1))
print(np.linalg.matrix_power(var,3)) # must be square
print(np.linalg.matrix_power(var,0)) # identity matrix
#Determinate
print(np.linalg.det(var))

[[1 2 3]
 [4 5 7]
 [1 4 5]]
[[1 4 1]
 [2 5 4]
 [3 7 5]]
[[1 4 1]
 [2 5 4]
 [3 7 5]]
[[-0.75  0.5  -0.25]
 [-3.25  0.5   1.25]
 [ 2.75 -0.5  -0.75]]
[[-0.18281938  0.35022026 -0.01762115]
 [ 0.1277533  -0.08810573  0.04845815]]
[[140 272 364]
 [357 695 930]
 [246 478 640]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
4.000000000000002
