**1. NumPy Arrays**

In [451]:
import numpy as np
#1D Array
arr1=np.array([1,2,3,4,5,4,5,6,7,10])
print(arr1)
print(type(arr1))
print(arr1.ndim)

#2D Array
arr2=np.array([[1,2,3],
       [9,2,3]])
print(arr2)
print(type(arr2))
print(arr2.ndim)

#3D Array
arr3=np.array([[[1,2,3],[3,4,5]],[[12,12,13],[4,4,1]]])
print(arr3)
print(type(arr3))
print(arr3.ndim)

[ 1  2  3  4  5  4  5  6  7 10]
<class 'numpy.ndarray'>
1
[[1 2 3]
 [9 2 3]]
<class 'numpy.ndarray'>
2
[[[ 1  2  3]
  [ 3  4  5]]

 [[12 12 13]
  [ 4  4  1]]]
<class 'numpy.ndarray'>
3


**2. Array Attributes**

In [454]:
import numpy as np
array1=np.array([1.3,2,3,6.1])
array2=np.array([[1,2,3],
       [9,2,3]])
#For 1D Array
print(array1.ndim)# Number of dimensions
print(array1.shape)# Shape (rows, columns)
print(array1.size)# Total elements
print(array1.dtype) # Data type
print(array1.itemsize)# Size (bytes) of each element

#For 2D Array
print(array2)
print(type(array2))
print(array2.ndim)
print(array2.size)
print(array2.dtype)
print(array2.itemsize)

1
(4,)
4
float64
8
[[1 2 3]
 [9 2 3]]
<class 'numpy.ndarray'>
2
6
int32
4


**3. Array Creation Methods**

In [457]:
                                 #3.1:Basic arrays
import numpy as np
#3.1.1:Zeros
zeros=np.zeros(4)#1D array
print(zeros)
zeros1=np.zeros((3,4))#2D array(3*4)
print(zeros1)
zeros2=np.zeros((2,3,4))#2 blocks,Each block has 3 rows,Each row has 4 columns
print(zeros2)#3D array

#3.1.2:Ones
ones=np.ones(3)#1D array
print(ones)
ones1=np.ones((3,2))#2D array
print(ones1)
ones2=np.ones((2,2,3))#3D array
print(ones2)

#3.1.3:Full
full=np.full((4,),6)#1D array filled with 6
print(full)
full1=np.full((2,3),7)#2D array filled with 7
print(full1)
full2=np.full((2,3,2),8)#3D array filled with 8
print(full2)

#3.1.4:Empty 
empty=np.empty(4)#1D array filled with 0
print(empty)
empty2=np.empty((2,4))#2D array filled with 0
print(empty2)
empty3=np.empty((2,3,4))#3D array filled with 0
print(empty3)

#3.1.5:Eye --> Identity matrix
eyes=np.eye(3)#1D array
print(eyes)

                                 #3.2:Range arrays
#3.2.1:arrage
print(np.arange(0,10,2))#arange(start,end,step)

#3.2.2:linspace 
print(np.linspace(10,20,5))#(start,end,numbers)
                                #3.3:Random arrays
#3.3.1:rand() function

Rand_1D=np.random.rand(10)#np.random.rand(n)-->1D array of n random floats between 0 and 1
print(Rand_1D)
Rand_2D=np.random.rand(2,3)#np.random.rand(n,m)-->2D array of (n*m) random floats between 0 and 1
print(Rand_2D)
Rand_3D=np.random.rand(2,3,4)#np.random.rand(n,m,p)-->2D array of (n*m*p) random floats between 0 and 1
print(Rand_3D)

#3.3.2:randn() function #close to zero ,include positive and Negative
Randn_1D=np.random.randn(4)#1D array
print(Randn_1D)
Randn_2D=np.random.randn(2,4)#2D array
print(Randn_2D)
Randn_3D=np.random.randn(2,2,3)#3D array
print(Randn_3D)

#3.3.3:ranf() function #Random floats in [0, 1)
Ranf_1D=np.random.ranf(3) #1D array
Ranf_2D=np.random.ranf((3,3)) #2D array
Ranf_3D=np.random.ranf((2,3,2))#3D array
print(Ranf_1D,Ranf_2D,Ranf_3D)

#3.3.4:Randint(low, high=None, size=None)
randint_1D=np.random.randint(0,10,2)#1D array ,select n numbers from k to m (k,m,n) 
randint_2D=np.random.randint(0,10,(2,2))#2D array
randint_3D=np.random.randint(0,10,(2,3,2))#3D array
print(randint_1D,randint_2D,randint_3D)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[6 6 6 6]
[[7 7 7]
 [7 7 7]]
[[[8 8]
  [8 8]
  [8 8]]

 [[8 8]
  [8 8]
  [8 8]]]
[0. 0. 0. 0.]
[[2.12199579e-314 2.12199579e-314 1.27319747e-313 1.27319747e-313]
 [3.95252517e-323 2.12199579e-314 1.06099790e-313 2.12199579e-314]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[10.  12.5 15.  17.5 20. ]
[0.91757311 0.65205756 0.86749309 0.51470116 0.52261769 0.7034129
 0.05114176 0.67247969 0.15792638 0.26514995]
[[0.99095842 0.67896109 0.56341901]
 [0.9796226  0.53447233 0.44824533]]
[[[0.77396809 0.32857639 0.18156799 0.57551376]
  [0.99084906 0.44790035 0.18567045 0.84922261]
  [0.63636995 0.01780727 0.8128764  0.27075903]]

 [[0.838

**4. Indexing and Slicing**

In [460]:
#4.1:Indexing
arr_1D=np.array([1,2,3,4,5,6,7,8])#1D array indexing
print(arr_1D[1],arr_1D[-3])
arr_2D=np.random.randint(2,10,(3,3))#2D array indexing
print(arr_2D)
print(arr_2D[1,2])
#arr_3D=np.random.randn(2,3,2)#3D array indexing 
Ranf_3D=np.random.ranf((2,3,2))#3D array indexing 
print(arr_3D)
print(arr_3D[0,1,1])

#4.2:Slicing 
array_1D=np.arange(0,15,2)#1D array
print(array_1D)
print(array_1D[1:4:2])#[start,end,step]

array_2D=np.random.randint(0,10,(4,4))#2D array
print(array_2D)
print(array_2D[1:3,1:4])#arr[row_start:row_end, col_start:col_end]
print(array_2D[:,[1,3]])#Selecting specific columns
print(array_2D[[2,3],:])#Selecting specific rows
print(array_2D[[0,3],:3])#Selecting specific rows or columns

array_3D=np.random.randint(10,20,(3,4,3))#3D array
print(array_3D)
print(array_3D[0:2,1:3,2:3])#arr[depth_start:depth_end, row_start:row_end, col_start:col_end]

2 6
[[9 5 4]
 [6 3 2]
 [5 3 9]]
2
[[[-0.01933766 -0.06791163]
  [-0.20481134  0.0024951 ]
  [ 1.65620021 -0.66919775]]

 [[ 1.84336915 -0.60610675]
  [-1.45799341 -0.43150479]
  [ 0.01099194  0.87468704]]]
0.002495095797715093
[ 0  2  4  6  8 10 12 14]
[2 6]
[[2 6 3 0]
 [6 7 5 0]
 [2 1 3 7]
 [4 9 5 7]]
[[7 5 0]
 [1 3 7]]
[[6 0]
 [7 0]
 [1 7]
 [9 7]]
[[2 1 3 7]
 [4 9 5 7]]
[[2 6 3]
 [4 9 5]]
[[[16 12 16]
  [14 14 16]
  [14 14 10]
  [11 18 19]]

 [[14 13 19]
  [19 18 11]
  [12 13 11]
  [14 18 14]]

 [[12 10 15]
  [17 11 14]
  [19 10 14]
  [16 19 12]]]
[[[16]
  [10]]

 [[11]
  [11]]]


**5. Array Operations (Element-wise)**

In [463]:
#5.1:Arithmetic
x=np.arange(10,100,10)#arange(start,end,step)
y=np.linspace(10,100,9)#linspace(start,end,numbers)
print(x,y)
print(y+x)
print(y-x)
print(y*x)
print(y/x)
print(y*2)
print(x**2)
print(y//x)
k=np.array([20,4,60,10,70])
j=np.array([2,20,10,5,6])
print(k//j)
print(j//k)

#5.2:Mathematical functions
array_1D=np.arange(1,10,2)
array_2D=np.array([[2,4],[5,7]])
array_3D=np.random.ranf((2,3,2))#0 to 1 floats
print(np.sqrt(array_1D),np.sqrt(array_2D),np.sqrt(array_3D))
print(np.exp(array_1D),np.exp(array_2D),np.exp(array_3D))
print(np.log10(array_1D),np.log10(array_2D),np.log10(array_3D))
print(np.log2(array_1D),np.log2(array_2D),np.log2(array_3D))
print(np.sin(array_1D),np.arctan(array_2D),np.cos(array_3D))
print(np.max(array_1D),np.max(array_2D),np.max(array_3D))
print(np.sum(array_1D),np.sum(array_2D),np.sum(array_3D))
print(np.mean(array_1D),np.mean(array_2D),np.mean(array_3D))
print(np.std(array_1D),np.std(array_2D),np.std(array_3D))
print(np.median(array_1D),np.median(array_2D),np.median(array_3D))
print(np.var(array_1D),np.var(array_2D),np.var(array_3D))
print(np.power((array_1D),2),np.power((array_2D),2),np.power((array_3D),2))

#5.3:Inverse and degree conversion
print(np.arcsin(1))# sin⁻¹(1) = π/2,Inverse
print(np.deg2rad(180))#or np.radians(180) ,degrees → radians
print(np.rad2deg(np.pi/3))#or np.degrees(np.pi/3) ,radians to degrees

[10 20 30 40 50 60 70 80 90] [ 10.    21.25  32.5   43.75  55.    66.25  77.5   88.75 100.  ]
[ 20.    41.25  62.5   83.75 105.   126.25 147.5  168.75 190.  ]
[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]
[ 100.  425.  975. 1750. 2750. 3975. 5425. 7100. 9000.]
[1.         1.0625     1.08333333 1.09375    1.1        1.10416667
 1.10714286 1.109375   1.11111111]
[ 20.   42.5  65.   87.5 110.  132.5 155.  177.5 200. ]
[ 100  400  900 1600 2500 3600 4900 6400 8100]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[10  0  6  2 11]
[0 5 0 0 0]
[1.         1.73205081 2.23606798 2.64575131 3.        ] [[1.41421356 2.        ]
 [2.23606798 2.64575131]] [[[0.54212853 0.70851181]
  [0.81651931 0.41117065]
  [0.79105001 0.90582702]]

 [[0.77969758 0.61876094]
  [0.80101786 0.74337073]
  [0.98141199 0.88645868]]]
[2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 8.10308393e+03] [[   7.3890561    54.59815003]
 [ 148.4131591  1096.63315843]] [[[1.34165421 1.65200381]
  [1.94780633 1.18419273]
  [1.

**5. Broadcasting**

In [ ]:
#Broadcasting Allows operations between arrays of different shapes.
#If the dimensions are equal →compatible.
#If one of them is 1 → can stretch.
#Otherwise → not compatible.
A=np.array([[1,2,3],[4,6,7]])
B=np.array([1,3,4])
print(A+B)
print(A+10)#Scalar and array
print(B*2)

[[ 2  5  7]
 [ 5  9 11]]
[[11 12 13]
 [14 16 17]]


**6. Reshaping Array**

In [469]:
import numpy as np 
a=np.random.randn(10)
#print(a)
b=a.reshape(2,5)
print(b)
c=np.arange(12)
print(c.reshape(3,4))#2D shape
d=c.reshape(2,3,2)
print(d)#3D shape
print(c.reshape(3,-1))#Using -1 (Automatic Dimension)
print(b.flatten())#2D to 1D
#print(b.ravel())#Similar but returns view
print(c.flatten())#3D to 1D
#print(c.ravel())Similar but returns view

[[ 0.70382679  1.64781691  0.31467441  0.84125334  0.18817187]
 [-0.8215954   0.46791982  0.27902573 -1.08670734  0.96378701]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0.70382679  1.64781691  0.31467441  0.84125334  0.18817187 -0.8215954
  0.46791982  0.27902573 -1.08670734  0.96378701]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


**7.Stacking & Splitting**

In [472]:
#7.1:Stacking
array1=np.linspace(0,10,6)
array2=np.arange(4,10,1)

print(array1)
print(array2)
print(np.vstack((array1,array2)))#returns 2D array,vertical stack
print(np.hstack((array1,array2)))#returns 1D array,horizontal stack

#7.2:Splitting
print(np.split(array1,3))
print(np.split(array2,2))

[ 0.  2.  4.  6.  8. 10.]
[4 5 6 7 8 9]
[[ 0.  2.  4.  6.  8. 10.]
 [ 4.  5.  6.  7.  8.  9.]]
[ 0.  2.  4.  6.  8. 10.  4.  5.  6.  7.  8.  9.]
[array([0., 2.]), array([4., 6.]), array([ 8., 10.])]
[array([4, 5, 6]), array([7, 8, 9])]


**8.Boolean Indexing & Filtering**

In [475]:
array1=np.random.ranf(10)# floats between 0 to 1
print(array1)
print(array1>0.5)

[0.87378196 0.64754861 0.6081757  0.10590164 0.9348788  0.74692176
 0.16627281 0.28173236 0.56107428 0.48597205]
[ True  True  True False  True  True False False  True False]


**9.Matrix Operations**

In [478]:
A=np.random.ranf((3,3))
B=np.random.randint(0,5,(3,3))
print(A,B)
print(A+B)
print(A*B)# Element-wise
print(np.dot(A,B))# Matrix multiplication
print(A.T)#transpose
print(np.linalg.inv(A))
print(np.linalg.det(B))

[[0.39351765 0.71183086 0.42426569]
 [0.63208337 0.38895066 0.0714215 ]
 [0.81129019 0.18526941 0.75319698]] [[3 4 0]
 [1 4 2]
 [3 1 3]]
[[3.39351765 4.71183086 0.42426569]
 [1.63208337 4.38895066 2.0714215 ]
 [3.81129019 1.18526941 3.75319698]]
[[1.18055294 2.84732345 0.        ]
 [0.63208337 1.55580264 0.142843  ]
 [2.43387056 0.18526941 2.25959094]]
[[3.16518088 4.84565973 2.6964588 ]
 [2.49946528 4.15555763 0.99216583]
 [4.87873091 4.73943538 2.63012977]]
[[0.39351765 0.63208337 0.81129019]
 [0.71183086 0.38895066 0.18526941]
 [0.42426569 0.0714215  0.75319698]]
[[-1.02929775  1.683624    0.42014078]
 [ 1.53862344  0.17591219 -0.88336659]
 [ 0.73021973 -1.85675038  1.09241638]]
42.00000000000002


**10.Copy vs View**

In [481]:
#View
a=np.array((1,2,3,4,5))#array from tuple 
b=a.view() # view → shares data
b[4] = 6
print(a,b)

#Copy 
d=np.arange(0,10,2)
e=d.copy() # copy → independent
e[3]=5
print(d,e) # unaffected

[1 2 3 4 6] [1 2 3 4 6]
[0 2 4 6 8] [0 2 4 5 8]
