In [11]:
import numpy as np
#Small Dataset
%timeit [i for i in range(10)]
%timeit np.arange(10)

461 ns ± 76.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
674 ns ± 20.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [17]:
#Heterogeneous Data
%timeit list=[1,2.4,"Hello"]
%timeit list1=np.array([1,2.4,"Hello"])

53 ns ± 4.91 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
1.41 μs ± 117 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [49]:
#Array Dimension Check
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9])
y=np.array([[1,2,3,4],[4,2,3,4]])
z=np.array([[[12,2],[23,2]],[[1,2],[1,5]]])
print(x,"\n",y,"\n",z)
print(x.ndim,z.ndim,y.ndim)

[1 2 3 4 5 6 7 8 9] 
 [[1 2 3 4]
 [4 2 3 4]] 
 [[[12  2]
  [23  2]]

 [[ 1  2]
  [ 1  5]]]
1 3 2


In [45]:
#Create NumPy Arrays with Random Numbers
#Random rand() value between 0 to 1
var=np.random.rand(5)
print(var)
#Random randn() value close to zero,negative or positive
var2=np.random.randn(5)#Standard Normal (Gaussian) distribution
print(var2)
var3=np.random.ranf(5)#Uniform distribution [0.0, 1.0)
print(var3)
#Random randint(start,end,number) #choose a or more random value from the range
var4=np.random.randint(10)
print(var4)
var5=np.random.randint(1,10,5)
print(var5)

[0.52477859 0.10608123 0.82990678 0.44785732 0.38173701]
[ 1.92394049  0.43410507  0.11412509  0.28007068 -0.47638828]
[0.61808427 0.7456631  0.47861741 0.66532912 0.25715215]
6
[2 3 9 6 2]


In [16]:
import numpy as np
variable=np.array([1,2,3,4,5,6.3,1,3,4],dtype=np.int8)
print(type(variable.dtype))

<class 'numpy.dtypes.Int8DType'>
